chabookmark: misc cleanup
* remove dead code
* dedupe sections on add (having the same section twice breaks the
  algorithm)

diff --git a/adapter/protocol/chabookmark b/adapter/protocol/chabookmark
--- a/adapter/protocol/chabookmark
+++ b/adapter/protocol/chabookmark
@@ -51,20 +51,12 @@ urldec() {
 	printf '%s\n' "$1" | sed 's/+/ /g' | "${CHA_LIBEXEC_DIR:-/usr/local/libexec/chawan}"/urldec
 }
 
-urlenc() {
-	printf '%s\n' "$1" | "$CHA_LIBEXEC_DIR"/urlenc
-}
-
 post_only() {
 	test "$REQUEST_METHOD" = POST || die InvalidMethod
 }
 
-safe_printf() {
-	printf "$@" || die "InternalError error writing file"
-}
-
 safe_println() {
-	safe_printf '%s\n' "$1"
+	printf '%s\n' "$1" || die "InternalError error writing file"
 }
 
 safe_rm() {
@@ -144,14 +136,13 @@ new() {
 		exit 1
 	fi
 	if ! test -f "$bookmark_file"; then init || exit 1; fi
-	if test -n "$new_section"
-	then	section=$new_section
-		safe_printf '\n## %s\n' "$new_section" >>"$bookmark_file"
-	elif test -z "$section"
+	if test -n "$new_section"; then section=$new_section; fi
+	if test -z "$section"
 	then	die "InternalError section not specified"
 	fi
 	new_tmp="$bookmark_file~"
 	new_found=0
+	new_entry="* [$title]($url)"
 	safe_rm "$new_tmp"
 	while read -r line
 	do	safe_println "$line" >>"$new_tmp"
@@ -167,13 +158,19 @@ new() {
 				*)	safe_println "$line" >>"$new_tmp";;
 				esac
 			done
-			safe_println "* [$title]($url)" >>"$new_tmp"
+			safe_println "$new_entry" >>"$new_tmp"
 			if test "$new_found" = 1
 			then	safe_println '' >>"$new_tmp"
 			else	new_found=1
 			fi
 		fi
 	done <"$bookmark_file"
+	if test "$new_found" = 0 && test -n "$new_section"
+	then	safe_println '' >>"$new_tmp"
+		safe_println "## $new_section" >>"$new_tmp"
+		safe_println '' >>"$new_tmp"
+		safe_println "$new_entry" >>"$new_tmp"
+	fi
 	mv "$new_tmp" "$bookmark_file" || die "InternalError could not move temp file"
 	view
 }
