mailcap, loader: browsecap improvements
* add lenient parsing mode for browsecap that accepts extension fields
  without x- prefix (they aren't really extensions since the format itself
  is non-standard)
* implement pseudo-shell parsing for cgioutput
* migrate urimethodmap -> browsecap (except for bonus, will have to do that
  later)
* define "cgi-bin:" in browsecap (i.e. it's no longer a built-in scheme)
* fix some broken handles not being closed in loadResource
* fix error code on CGI exec error (we can't send negative error codes from
  there)

At last, this deprecates urimethodmap.  It will be kept for w3m
compatibility indefinitely, but browsecap is superior in every aspect, so
use that if you can.

diff --git a/adapter/protocol/gopher b/adapter/protocol/gopher
--- a/adapter/protocol/gopher
+++ b/adapter/protocol/gopher
@@ -1,17 +1,29 @@
 #!/bin/sh
 
-opath=/${MAPPED_URI_PATH#"${MAPPED_URI_PATH%%[!/]*}"}
+die() {
+	echo "Cha-Control: ConnectionError $1 $2"
+	exit 1
+}
+
+if test "$#" -ne 4
+then	die InternalError "usage: gopher [host] [port] [path] [query]"
+fi
+
+host=$1
+port=${2:-70}
+opath=/${3#"${3%%[!/]*}"}
 path0=$(printf '%s\n' "$opath" | "$CHA_LIBEXEC_DIR"/urldec)
 path=${path0##/?}
+query=$4
 t=${path0%%"$path"}
 t=${t##?}
 
-if test "$t" = 7 && test -z "$MAPPED_URI_QUERY"
+if test "$t" = 7 && test -z "$4"
 then	exec cat <<EOF
 Content-Type: text/html
 
 <!DOCTYPE html>
-<h1>Search $MAPPED_URI_SCHEME://$MAPPED_URI_HOST:$MAPPED_URI_PORT$opath</h1>
+<h1>Search gopher://$host:$port$opath</h1>
 <form><input type=search name=name autofocus></form>
 EOF
 else	LF='
@@ -29,9 +41,9 @@ Location: /1$opath
 EOF
 		;;
 	esac
-	query=$(printf '%s\n' "${MAPPED_URI_QUERY##*=}" | \
+	query=$(printf '%s\n' "${query##*=}" | \
 		sed 's/\+/ /g' | "$CHA_LIBEXEC_DIR"/urldec)
 	tab='	'
 	printf '%s\r\n' "$path${query:+"$tab"}${query##*=}" | \
-		"$CHA_LIBEXEC_DIR"/nc -m "$msg$LF" "$MAPPED_URI_HOST" "${MAPPED_URI_PORT:-70}"
+		"$CHA_LIBEXEC_DIR"/nc -m "$msg$LF" "$host" "$port"
 fi
diff --git a/adapter/protocol/spartan b/adapter/protocol/spartan
--- a/adapter/protocol/spartan
+++ b/adapter/protocol/spartan
@@ -1,13 +1,24 @@
 #!/bin/sh
 # Adapter for the spartan protocol. See: spartan://mozz.us
 
-MAPPED_URI_PORT=${MAPPED_URI_PORT:-300} # default port is 300
-MAPPED_URI_PATH=${MAPPED_URI_PATH:-/} # needs / for root
-if test "$REQUEST_METHOD" != POST && test "$MAPPED_URI_QUERY" = "input"
+die() {
+	echo "Cha-Control: ConnectionError $1 $2"
+	exit 1
+}
+
+if test "$#" -ne 4
+then	die InternalError "usage: spartan [host] [port] [path] [query]"
+fi
+
+host=$1
+port=${2:-300} # default port is 300
+path=${3:-/} # needs / for root
+query=$4
+if test "$REQUEST_METHOD" != POST && test "$query" = "?input"
 then	printf "Content-Type: text/html
 
 <!DOCTYPE html>
-<form method=POST action='\"$MAPPED_URI_PATH\"'>
+<form method=POST enctype=text/plain action='"$path"'>
 Input text to upload:
 <p>
 <textarea name=q></textarea>
@@ -19,9 +30,9 @@ fi
 CONTENT_LENGTH=${CONTENT_LENGTH:+$(($CONTENT_LENGTH - 2))} # skip q=
 CONTENT_LENGTH=${CONTENT_LENGTH:-0} # if missing, set to 0
 {
-	printf '%s %d\n' "$MAPPED_URI_HOST $MAPPED_URI_PATH" "$CONTENT_LENGTH"
+	printf '%s %d\n' "$host $path" "$CONTENT_LENGTH"
 	tail -c+3 # skip q=
-} | "$CHA_LIBEXEC_DIR"/nc "$MAPPED_URI_HOST" "$MAPPED_URI_PORT" | {
+} | "$CHA_LIBEXEC_DIR"/nc "$host" "$port" | {
 	IFS= read -r line
 	case $line in
 	'2 '*)	ctype=${line#2 }
